name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Generate Application Key
        run: php artisan key:generate

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest

    needs: [build, test]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to Server
        run: php artisan migrate --force && php artisan optimize
